# Development and Test environment configurations are listed here
# for convenience but generally shouldn't be used.
# 
# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

production:
  server: "http://ramfayeserver.herokuapp.com/faye"
  secret_token: "67e782ee18f0b89af9f3278666b8432dd9c80e5f09de68551d63278253cc23bb"
  signature_expiration: 86400 # one day	